board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('regist/',views.regist,name='regist'),
    path('detail/<int:pk>',views.detail,name='detail')
]

djangoPractice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda r: redirect('board:index')),
    path('board/', include('board.urls')),
]

board/models.py
from django.db import models

# Create your models here.
from django.db import models
class Board(models.Model) :
    title = models.CharField(max_length=200, verbose_name='글 제목', help_text='*최목은 최대 100자 이내')
    author = models.TextField(max_length=100, verbose_name='글쓴이')
    content = models.TextField(verbose_name='글 내용')
    published_date = models.DateTimeField(auto_now=True, verbose_name='등록(수정)일')
    def __str__(self):
    #__str__()  함수는 객체가 생성되면 문자열로 반활해주는 함수, title(제목)반환환하도록 지정함
        return self.title

board/forms.py
from django import forms
from django.forms import widgets
from .models import Board

class RegistForm(forms.ModelForm):
    print(forms.ModelForm,"확니")
    class Meta:
        model = Board
        fields = ['title','author','content']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'author': forms.TextInput(attrs={'class':'form-control'}),
            'content':forms.Textarea(attrs={'class':'form-control','rows':10})
        }
# class UpdateForm(forms.)

board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Board
from .forms import RegistForm
# Create your views here.
def index(request):
    board_list=Board.objects.all().order_by('-id')
    context = {'board_list':board_list}
    return render(request, 'board/index.html', context)
def regist(request):
    if request.method== 'POST' :
        form = RegistForm(request.POST)
        print(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect('board:index')
    else:
        form = RegistForm()
    context = {'form':form}
    return render(request,'board/regist_form.html',context)
def detail(request, pk):
    board_list = get_object_or_404(Board, id=pk)
    context = {'board_list':board_list}
    return render(request, 'board/detail.html',context)

board/templates/board/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row pt-4 my-3">
        <h3>글 읽기</h3>
    </div>
</div>
<div class="row my-3"></div>
    <table class="table table-bordered">
        <tr>
            <td>[글제목] : {{board_list.title}}</td>
        </tr>
        <tr>
            <td>
                <p>[글 내용]</p>
                {{ board_list.content }}
                <p>[{{board_list.published_date}}]</p>
            </td>
        </tr>
    </table>
    <form action="" method="put">
        {% csrf_token %}
        {{form.as_p}}
        <div style="padding: 5px 50px; float:right">
<!--            <input class="btn btn-primary" type="submit" value="글등록">-->
            <a href="{% url 'board:index' %}" class="btn btn-primary">글목록</a>
        </div>
    </form>
{% endblock %}

board/templates/board/index.html
{% extends 'base.html' %}
{% block content %}
 <div class="container">
     {{board_list}}

     <div class="row pt-4 my-3"><div class="col-md-12"><h3>게시판</h3></div></div>
     <div class="row my-3">
         <table class="table table-hover table-boardered">
            <thead>
                <th>No</th>
                <th>작성자</th>
                <th>내용</th>
            </thead>
             <tbody>
                {% for post in board_list %}
                <tr>
                    <td>
                        <a href="#">
                            {{forloop.revcounter}}
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'board:detail' post.id %}">{{post.title}}</a>
                    </td>
                    <td>
                        {{post.author}}
                    </td>
                    <td>
                        {{forloop.author}}
                    </td>
                    <td>
                        {{forloop.author}}
                    </td>
                    <td>
                        {{forloop.content}}
                    </td>
                    <td>
                        {{forloop.published}}
                    </td>
                </tr>
                {% endfor %}
             </tbody>
        </table>
         <div style="padding:2px 20px; float: right">
             <a href="{% url 'board:regist' %}" class="btn btn-primary">글등록</a>
         </div>
     </div>
 </div>
{% endblock %}

board/templates/board/regist_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row pt-4 my-3">
        <h3>글 등록</h3>
    </div>
</div>
<div class="row my-3"></div>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <div style="padding: 5px 50px; float:right">
            <input class="btn btn-primary" type="submit" value="글등록">
            <a href="{% url 'board:index' %}" class="btn btn-primary">글목록</a>
        </div>
    </form>
{% endblock %}